version: "3"
services:
  vodacom-backend:
    container_name: vodacom
    env_file: .env
    restart: always
    environment:
      - STATE=$STATE
      - PORT=$PORT
      - MONGODB_URI=$MONGODB_URI
      - DB_NAME=$DB_NAME
      - CLIENT_APP=$CLIENT_APP
      - EMAIL_VER_SECRET=$EMAIL_VER_SECRET
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_USE_TLS=$EMAIL_USE_TLS
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - PUBNUB_PUB_KEY=$PUBNUB_PUB_KEY
      - PUBNUB_SUB_KEY=$PUBNUB_SUB_KEY
      - AWS_BUCKET_NAME=$AWS_BUCKET_NAME
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
