version: "3"
services:
  vodacom:
    container_name: vodacom
    env_file: .env
    restart: always
    environment:
      - STATE=$STATE
      - PORT=$PORT
      - MONGODB_URI=$MONGODB_URI
      - DB_NAME=$DB_NAME
      - CLIENT_APP=$CLIENT_APP
      - EMAIL_VER_SECRET=$EMAIL_VER_SECRET
      - CLOUDINARY_URL=$CLOUDINARY_URL
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_USE_TLS=$EMAIL_USE_TLS
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - PUBNUB_PUB_KEY=$PUBNUB_PUB_KEY
      - PUBNUB_SUB_KEY=$PUBNUB_SUB_KEY
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
